import React from 'react'
import "../dashboard/globals.css"
import { Metadata } from 'next'


export const metadata: Metadata = {
    title: 'Taches page',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
} :{
    children: React.ReactNode
}) {
    return (
        <>
        <body>
            {children}
        </body>
        </>
    )
}


