import type { Metadata } from "next";
import "../dashboard/globals.css";

export const metadata: Metadata = {
  title: "signIn page",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        <main>{children}</main>
      </body>
    </html>
  )
}
