import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";
import Sidebar from "./sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Abdoul-Dashoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
      <Header />
      <div className="flex">
        <div className="">
        <Sidebar />
        </div>
        <div className="w-4/5 justify-start">
            {children}
        </div>
      </div>
      <Footer />
      </body>
      </html>
  );
}
